cibr-qcri/toshi

web/src/components/Header/Menu/General/MenuGeneral-styles.js, web/src/components/Header/Menu/General/MenuGeneral.js, web/src/components/Header/Menu/General/index.js, web/src/components/Header/Menu/HeaderMenu.js
=> Issue #35: Added home navigation to side drawer

api/utils/mail.js, web/package-lock.json, web/src/components/WalletInfoRaw/Body/WalletInfoBody-styles.js, web/src/components/WalletInfoRaw/Body/WalletInfoBody.js
=> Add an info icon and a tooltip for the Balance field

web/src/components/Account/Actions/AccountActions-styles.js, web/src/components/Account/Actions/AccountActions.js, web/src/components/Account/Form/AccountForm-styles.js, web/src/components/Account/Form/AccountForm.js, web/src/components/ButtonRaw/ButtonRaw-styles.js, web/src/components/ButtonRaw/ButtonRaw.js, web/src/components/ButtonRaw/index.js, web/src/components/Header/Header.js, web/src/components/Header/Menu/General/MenuGeneral.js, web/src/components/SignIn/Form/SignInForm-styles.js, web/src/components/SignIn/Form/SignInForm.js, web/src/components/SignUp/Form/SignUpForm-styles.js, web/src/components/SignUp/Form/SignUpForm.js
Closes #34.
Upon checking, I found out that adding a loading indicator looks ugly. Disabling the button upon signing in/out looked the best. Check the SS below:
=> Issue #34: Disable buttons when signing in or out

web/src/components/SearchBoxRaw/SearchBoxRaw.js
=> Issue #32: Disable spell check on search boxes

web/src/components/DataTableRaw/DataTableRaw.js, web/src/components/Header/Header-styles.js, web/src/components/Header/Menu/Info/MenuInfo.js, web/src/components/Header/Menu/Outreach/MenuOutreach.js, web/src/components/Wallet/TopContent/Labels/WalletTopContentLabels.js, web/src/components/Wallet/TopContent/Links/WalletTopContentLinks.js, web/src/components/WalletInfoRaw/Title/WalletInfoTitle.js
=> Issue #29: Changed app links to not open a new page

api/middleware/wallet/labels.js, api/utils/wallet.js
- Closes https://github.com/cibr-qcri/toshi/issues/42
=> Issue #15:: Shortened onion domains in labels

web/src/components/Search/Search.js
=> Issue #30: Redirect to wallet view if there is only one search result

api/utils/common.js, api/utils/wallet.js, web/src/components/Wallet/Tabs/Transactions/WalletTransactions.js
=> Issue #36: Added transaction timestamp to wallet view

web/src/components/SearchBoxRaw/SearchBoxRaw.js
=> Fix search box styling for dark mode on mobile devices

api/utils/wallet.js, web/src/components/WalletInfoRaw/Body/WalletInfoBody.js
=> Issue #28: If there are no top category or label, return "Multiple"

web/src/components/App/App.js, web/src/components/Header/Header-styles.js, web/src/components/Header/Menu/General/MenuGeneral.js, web/src/components/Header/Menu/Outreach/MenuOutreach.js, web/src/components/Search/Search-styles.js, web/src/components/Terms/Terms-styles.js, web/src/components/Terms/Terms.js, web/src/components/Terms/index.js
=> Issue #52: Added terms of service page

api/middleware/wallet/searchResults.js, api/models/Search.js, api/utils/wallet.js, web/src/store/actions/search/thunks.js, web/src/utils/common.js
- Closes https://github.com/cibr-qcri/toshi/issues/18
=> Adding wallet search support

api/middleware/wallet/searchResults.js, api/utils/wallet.js, web/src/components/SearchBoxRaw/SearchBoxRaw.js
- Closes https://github.com/cibr-qcri/toshi/issues/24
=> Fix #24: GP search query to handle special characters

api/middleware/wallet/searchResults.js, api/utils/wallet.js, web/src/components/Search/Results/Label/ResultsLabel-styles.js, web/src/components/Search/Results/Results-styles.js, web/src/components/Search/Results/Results.js, web/src/components/WalletInfoRaw/Body/WalletInfoBody-styles.js, web/src/components/WalletInfoRaw/WalletInfoRaw.js, web/src/store/actions/search/creators.js, web/src/store/actions/search/thunks.js, web/src/store/actions/search/types.js, web/src/store/reducers/search.js
=> Add sorting feature

web/src/components/Wallet/Tabs/WalletTabs.js, web/src/components/Wallet/Wallet.js, web/src/store/actions/index.js
=> Fixed a bug where wallet info is not properly updated

api/controllers/tags.js, api/models/AddressTag.js, api/models/WalletTag.js, api/routes/tags.js, web/src/components/Header/Menu/Outreach/MenuOutreach.js, web/src/components/TagDialog/Form/TagDialogForm-schema.js, web/src/components/TagDialog/Form/TagDialogForm-styles.js, web/src/components/TagDialog/Form/TagDialogForm.js, web/src/components/TagDialog/TagDialog.js, web/src/store/actions/dialog/creators.js, web/src/store/reducers/dialog.js, web/src/utils/common.js
- Closes https://github.com/cibr-qcri/toshi/issues/63
=> #Fix 63: Adding address report support 

api/middleware/wallet/topLinks.js, api/utils/wallet.js, web/src/components/Wallet/TopContent/Links/WalletTopContentLinks.js, web/src/constants/wallet/graphVizOptions.js
- Closes https://github.com/cibr-qcri/toshi/issues/21
=> Fix #21: Change node size relative to wallet size

api/middleware/wallet/searchResults.js, api/middleware/wallet/topWalletResults.js, api/utils/wallet.js, web/src/components/WalletResultsRaw/WalletResultsRaw-styles.js, web/src/components/WalletResultsRaw/WalletResultsRaw.js, web/src/store/actions/search/creators.js, web/src/store/actions/search/thunks.js, web/src/store/actions/search/types.js, web/src/store/reducers/search.js
=> Implement order by ascending/descending

api/middleware/wallet/topWalletResults.js, api/utils/wallet.js, web/src/components/Search/Search.js, web/src/components/TopWallets/TopWallets.js, web/src/components/WalletResultsRaw/Label/ResultsLabel.js, web/src/components/WalletResultsRaw/WalletResultsRaw.js, web/src/store/actions/index.js
- Closes https://github.com/cibr-qcri/toshi/issues/67
=> Fix #67: Adding btc_balance into wallet search

api/utils/wallet.js
=> Fixed search wallet by transaction query

api/middleware/wallet/labels.js, api/utils/wallet.js, web/src/components/DataTableRaw/DataTableRaw-styles.js, web/src/components/DataTableRaw/DataTableRaw.js
- Closes https://github.com/cibr-qcri/toshi/issues/74
=> Fix #74: Fixing multiple tags for same address issue

api/jobs/computeStats.js, web/src/components/Header/Menu/HeaderMenu-styles.js, web/src/components/Header/Menu/HeaderMenu.js
=> Adds synced block height to side bar

web/src/components/App/App.js
=> Fixes a bug where the stats are not fetched on startup
